FROM node:18-alpine AS production

# Declaring env
ENV NODE_ENV production

#RUN mkdir site

WORKDIR /reward-service

# Installing dependencies
COPY ./package.json /reward-service

RUN npm install

# Copying all the files in our project
COPY . .

CMD ["npm", "run", "start"]